language: go

go_import_path: github.com/viniciuslcpereira97/GoPracticeWS

go:
  - 1.8.3

env:
  global:
    - WS_CONFIG_DIR=$GOPATH/src/github.com/viniciuslcpereira97/GoPracticeWS/config

services:
  - mongodb