version: "2"

services:
    app:
        ports:
            - 8080:8888
        image: golang:1.8.3-alpine
        environment:
            - WS_CONFIG_DIR=/go/src/GoPracticeWS/config
        volumes:
            - .:/go/src/GoPracticeWS
        working_dir: /go/src/GoPracticeWS
        command: go run main.go
        links:
            - mongodb
    mongodb:
        image: mongo:3.4.9
